# Generated by Django 3.2.9 on 2023-04-10 01:01

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('introduce', models.TextField(max_length=80, verbose_name='简介')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('click_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('message_num', models.IntegerField(default=0, verbose_name='留言数')),
                ('love_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('cover', models.ImageField(blank=True, default='../static/cover/default1.jpg', max_length=200, null=True, upload_to='%y/%m/%d', verbose_name='封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='首页推荐')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'BlogInfo',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_tab', models.BooleanField(default=True, verbose_name='是否导航')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'TagInfo',
            },
        ),
    ]
