"""
Django settings for test092_blog project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bixtdrh4io-whdwrvnu$ssrk(qv8(+^!9zies5%&-un4deavu)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ------------以下是注册的项目--------------
    'users.apps.UsersConfig',
    'blogs.apps.BlogsConfig',
    'ckeditor_uploader',  # 上传图片
    'ckeditor',  # 富文本编辑器
    'pure_pagination',  # 分页器
    'comments.apps.CommentsConfig',  # 留言

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test092_blog.urls'
# ----------------------模板文件-----------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test092_blog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# ------------------------数据库----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "test092_blog",
        "USER": "root",
        "PASSWORD": 'mysql',
        "HOST": "localhost",
        "PORT": 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# --------------------设置语言和地区----------------------------------
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# --------------------静态文件存放路径---------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# --------------------媒体文件存放路径---------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------使用django的用户类----------------------------
AUTH_USER_MODEL = 'users.UserProfile'

# -----------------------使用邮箱验证码--------------------------------
# 发送邮件
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25
# 发送邮件的邮箱
EMAIL_HOST_USER = 'chi_luobo_fish@163.com'
# 在邮箱中设置的授权密码
EMAIL_HOST_PASSWORD = 'TFLZGLMBRZUKUSFF'
# 收件人看到的发件人
EMAIL_FROM = '请激活<chi_luobo_fish@163.com>'
# ------------------------富文本编辑器----------------------------------
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        # 'width': 500,
    },
}
# 上传图片地址 , 同media路径
CKEDITOR_UPLOAD_PATH = ''

PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,  # 展示出来的数字个数
    'MARGIN_PAGE_DISPLAYED': 3,  # 省略号前后有几个
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,  # 无效页码返回第一页
}
